#!/bin/sh
# AWS Lambda bootstrap script

# Get the handler name from the first argument passed to the bootstrap script
handler=$1

# Run in backfill mode or standard mode based on environment variable
if [ "$BACKFILL_MODE" = "true" ]; then
  echo "Running in backfill mode"
  exec python3 -m awslambdaric backfill_runner.lambda_handler
else
  echo "Running in standard mode"
  exec python3 -m awslambdaric lambda_function.lambda_handler
fi
