name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ncsoccer/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'
      - 'lambda_function.py'
      - 'runner.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'ncsoccer/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'
      - 'lambda_function.py'
      - 'runner.py'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: ncsoccer-scraper
  ENVIRONMENT: dev

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for relevant changes
        id: check
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          echo "Changes detected:"
          cat changes.txt

          # Check if any relevant files were changed
          if grep -q -E '^(ncsoccer/|Dockerfile|requirements.txt|lambda_function.py|runner.py)' changes.txt; then
            echo "Relevant changes detected"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant changes detected"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  build-service:
    needs: [check-changes]
    if: needs.check-changes.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name ncsoccer_scraper \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}